/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Client */

#ifndef _Included_Client
#define _Included_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Client
 * Method:    input
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Client_input
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
